# nav2_params.yaml
# Paramètres globaux pour Navigation2

amcl:
  ros__parameters:
    use_sim_time: False
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.1
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    scan_topic: "scan"
    min_particles: 500
    max_particles: 2000

map_server:
  ros__parameters:
    use_sim_time: False
    yaml_filename: "/home/asus/ros2_ws/maps/my_map.yaml"

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"

controller_server:
  ros__parameters:
    controller_frequency: 10.0
    min_x_velocity_threshold: 0.01
    min_y_velocity_threshold: 0.01
    min_theta_velocity_threshold: 0.01
    max_vel_x: 0.26
    min_vel_x: -0.26
    max_vel_theta: 1.82
    min_vel_theta: -1.82
    transform_tolerance: 0.1
    odom_topic: "odom"
    local_costmap:
      ros__parameters:
        update_frequency: 5.0
        publish_frequency: 2.0
        global_frame: "odom"
        robot_base_frame: "base_link"
        rolling_window: true
        width: 3.0
        height: 3.0
        resolution: 0.05
        plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
        static_layer:
          plugin: "nav2_costmap_2d::StaticLayer"
          map_subscribe_transient_local: true
        obstacle_layer:
          plugin: "nav2_costmap_2d::ObstacleLayer"
        inflation_layer:
          plugin: "nav2_costmap_2d::InflationLayer"
    global_costmap:
      ros__parameters:
        update_frequency: 5.0
        publish_frequency: 2.0
        global_frame: "map"
        robot_base_frame: "base_link"
        width: 10.0
        height: 10.0
        resolution: 0.05
        plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
        static_layer:
          plugin: "nav2_costmap_2d::StaticLayer"
          map_subscribe_transient_local: true
        obstacle_layer:
          plugin: "nav2_costmap_2d::ObstacleLayer"
        inflation_layer:
          plugin: "nav2_costmap_2d::InflationLayer"
    nav2_controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      critics: ["ObstacleFootprint", "GoalAlign", "PathAlign", "Oscillation", "PathDist"]
      ObstacleFootprint:
        plugin: "dwb_critics::ObstacleFootprintCritic"
      GoalAlign:
        plugin: "dwb_critics::GoalAlignCritic"
      PathAlign:
        plugin: "dwb_critics::PathAlignCritic"
      Oscillation:
        plugin: "dwb_critics::OscillationCritic"
      PathDist:
        plugin: "dwb_critics::PathDistCritic"

behavior_server:
  ros__parameters:
    plugin_names: ["back_up", "spin", "wait"]
    back_up:
      plugin: "nav2_behaviors/BackUp"
    spin:
      plugin: "nav2_behaviors/Spin"
    wait:
      plugin: "nav2_behaviors/Wait"

bt_navigator:
  ros__parameters:
    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"

waypoint_follower:
  ros__parameters:
    use_sim_time: False

velocity_smoother:
  ros__parameters:
    use_sim_time: False

